version: '3'
services:
  ejsik_smskey_backend:
    container_name: ejsik_smskey_backend
    build: .
    ports:
      - "18080:8080"
    environment:
      - SMSKEY_GH_TOKEN=${SMSKEY_GH_TOKEN}
      - SMSKEY_GH_ENDPOINT=https://api.github.com/repos/pmajkutewicz/smskey-sandbox/issues
    restart: always
    networks:
      - apache_apache

networks:
  apache_apache:
    external:
      name: apache_apache
